import AdminPanel from "@/components/admin/adminSideBar/AdminPanel";

export const metadata = {
  title: "Admin Dashboard",
  description: "Generated by Next.js",
};

export default function AdminLayout({ children }) {
  return (
    <div
      style={{
        display: "flex",
        minHeight: "100vh",
        backgroundColor: "#f8f9fa",
        gap: "20px",
      }}
    >
      <AdminPanel />

      <main style={{ flex: 1 }}>
        {children}
      </main>
    </div>
  );
}