import AdminPanel from "@/components/admin/adminSideBar/AdminPanel";

// В Next.js метаданные задаются так
export const metadata = {
  title: "Admin Dashboard",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru" suppressHydrationWarning>
      <body>
        <div
          style={{
            display: "flex",
            minHeight: "100vh",
            backgroundColor: "#f8f9fa",
            gap: "20px",
          }}
          suppressHydrationWarning
        >
          {/* Ваш сайдбар */}
          <AdminPanel />

          {/* Контент страницы (аналог Outlet) */}
          <main style={{ flex: 1 }}>
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}